import { Table, Thead, Tr, Tbody, Td, Th } from "@yakad/ui";

export default function example1() {
    return (
        <Table>
            <Thead>
                <Tr>
                    <Th>Year</Th>
                    <Th>Month</Th>
                    <Th>Number</Th>
                </Tr>
            </Thead>
            <Tbody>
                <Tr>
                    <Td>2024</Td>
                    <Td>January</Td>
                    <Td>1</Td>
                </Tr>
                <Tr>
                    <Td>2024</Td>
                    <Td>February</Td>
                    <Td>2</Td>
                </Tr>
                <Tr>
                    <Td>2024</Td>
                    <Td>March</Td>
                    <Td>3</Td>
                </Tr>
                <Tr>
                    <Td>2024</Td>
                    <Td>April</Td>
                    <Td>4</Td>
                </Tr>
                <Tr>
                    <Td>2024</Td>
                    <Td>May</Td>
                    <Td>5</Td>
                </Tr>
                <Tr>
                    <Td>2024</Td>
                    <Td>June</Td>
                    <Td>6</Td>
                </Tr>
            </Tbody>
            <Tr>
                <Td>2024</Td>
                <Td>July</Td>
                <Td>7</Td>
            </Tr>
            <Tr>
                <Td>2024</Td>
                <Td>Agust</Td>
                <Td>8</Td>
            </Tr>
            <Tr>
                <Td>2024</Td>
                <Td>September</Td>
                <Td>9</Td>
            </Tr>
            <Tr>
                <Td>2024</Td>
                <Td>October</Td>
                <Td>10</Td>
            </Tr>
            <Tr>
                <Td>2024</Td>
                <Td>November</Td>
                <Td>11</Td>
            </Tr>
            <Tr>
                <Td>2024</Td>
                <Td>December</Td>
                <Td>12</Td>
            </Tr>
        </Table>
    );
}
